[package]
name = "pi-contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = "20.0.0"

[dev-dependencies]
soroban-sdk = { version = "20.0.0", features = ["testutils"] }

[[test]]
name = "insurance_test"
path = "tests/insurance_test.rs"

[[test]]
name = "orchestrator_test"
path = "tests/orchestrator_test.rs"

[[test]]
name = "bidding_test"
path = "tests/bidding_test.rs"

[[test]]
name = "shares_test"
path = "tests/shares_test.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"
overflow-checks = true
lto = true
panic = "abort"